# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-30 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def load_categories_from_fixture(apps, schema_editor):
    from django.core.management import call_command
    call_command("loaddata", "story_categories.json")


def delete_categories(apps, schema_editor):
    Category = apps.get_model("story_manager", "Category")
    Category.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('story_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=2)),
            ],
        ),
        migrations.RunPython(load_categories_from_fixture, delete_categories),
        migrations.AddField(
            model_name='story',
            name='next_story',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='story_manager.Story')
        ),
        migrations.AddField(
            model_name='story',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='story_manager.Category')
        ),
        migrations.AddField(
            model_name='story',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
