# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-03 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_manager', '0002_add_lock_and_next'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='story',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
