# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-29 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_add_circles'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_json', models.TextField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Person')),
            ],
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('P', 'Parent'), ('C', 'Child'), ('F', 'Friend'), ('C', 'None')], max_length=1),
        ),
    ]
