# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-27 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_add_verbose'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='internal_name',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
