# Generated by Django 5.0.1 on 2024-02-09 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_connector', '0001_initial'),
        ('people', '0006_add_internal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.person'),
        ),
    ]
