DEFAULT_MILESTONE_STEPS = 400  # type: int
DEFAULT_MILESTONE_CALORIES = 1800  # type: float
DEFAULT_MILESTONE_DISTANCE = 2  # type: float
DEFAULT_MILESTONE_ACTIVE_MINUTES = 5  # type: int

MIN_STEPS = 300  # type: int
MIN_CALORIES = 1600  # type: float
MIN_DISTANCE = 0.5  # type: float
MIN_ACTIVE_MINUTES = 0  # type: int
