# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-11 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
def load_level_groups_from_fixture(apps, schema_editor):
    from django.core.management import call_command
    call_command("loaddata", "level_groups.json")


def delete_level_groups(apps, schema_editor):
    LevelGroup = apps.get_model("challenges", "LevelGroup")
    LevelGroup.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupchallenge',
            options={'ordering': ['end_datetime']},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='personfitnessmilestone',
            options={'ordering': ['end_datetime']},
        ),
        migrations.AddField(
            model_name='level',
            name='next_level',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenges.Level'),
        ),
        migrations.RunPython(load_level_groups_from_fixture, delete_level_groups),
        migrations.AddField(
            model_name='personfitnessmilestone',
            name='level_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='challenges.LevelGroup'),
        ),
    ]
