# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-13 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_add_more_relations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupchallenge',
            options={'get_latest_by': 'end_datetime'},
        ),
        migrations.AlterModelOptions(
            name='personfitnessmilestone',
            options={'get_latest_by': 'end_datetime'},
        ),
        migrations.AlterField(
            model_name='groupchallenge',
            name='completed_datetime',
            field=models.DateTimeField(blank=True),
        ),
    ]
