# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-13 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_update_model_meta_and_empty_completed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchallenge',
            name='completed_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
