# Generated by Django 5.0.1 on 2024-02-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_add_level_to_group_challenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchallenge',
            name='duration',
            field=models.CharField(choices=[('30m', '30 minutes'), ('1h', 'one hour'), ('2h', 'two hour'), ('12h', 'half-day'), ('1d', 'one-day'), ('2d', 'two-day'), ('3d', 'three-day'), ('3d', 'three-day'), ('7d', 'one-week')], max_length=16),
        ),
        migrations.AlterField(
            model_name='level',
            name='total_duration',
            field=models.CharField(choices=[('30m', '30 minutes'), ('1h', 'one hour'), ('2h', 'two hour'), ('12h', 'half-day'), ('1d', 'one-day'), ('2d', 'two-day'), ('3d', 'three-day'), ('3d', 'three-day'), ('7d', 'one-week')], max_length=16),
        ),
        migrations.AlterField(
            model_name='level',
            name='unit_duration',
            field=models.CharField(choices=[('30m', '30 minutes'), ('1h', 'one hour'), ('2h', 'two hour'), ('12h', 'half-day'), ('1d', 'one-day'), ('2d', 'two-day'), ('3d', 'three-day'), ('3d', 'three-day'), ('7d', 'one-week')], max_length=16),
        ),
        migrations.AlterField(
            model_name='personchallenge',
            name='unit_duration',
            field=models.CharField(choices=[('30m', '30 minutes'), ('1h', 'one hour'), ('2h', 'two hour'), ('12h', 'half-day'), ('1d', 'one-day'), ('2d', 'two-day'), ('3d', 'three-day'), ('3d', 'three-day'), ('7d', 'one-week')], max_length=16),
        ),
    ]
